# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

# ==================== Farm ====================

# ==================== Event ====================

EventA:
  EventDaily:
    StageFilter: |-
      A1 > A2 > A3
EventB:
  EventDaily:
    StageFilter: |-
      B1 > B2 > B3
EventC:
  EventDaily:
    StageFilter: |-
      C1 > C2 > C3
EventD:
  EventDaily:
    StageFilter: |-
      D1 > D2 > D3

EventClear:
  EventClear:
    StageFilter: |-
      T1 > T2 > T3 > HT1 > HT2 > HT3 > SP > EX > A1 > A2 > A3 > B1 > B2 > B3 > C1 > C2 > C3 > D1 > D2 > D3

# ==================== Reward ====================

Commission:
  Scheduler:
    Enable: true
Tactical:
  Scheduler:
    Enable: true
Research:
  Scheduler:
    Enable: true
Dorm:
  Scheduler:
    Enable: true
Meowfficer:
  Scheduler:
    Enable: true
Guild:
  Scheduler:
    Enable: true
Reward:
  Scheduler:
    Enable: true

# ==================== DailyReward ====================

Freebies:
  Scheduler:
    Enable: true

# ==================== DailyMission ====================

# ==================== Opsi ====================
